#!/usr/bin/env bash
set -euo pipefail

sbx_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
bin_dir="$HOME/.local/bin"
mkdir -p "$bin_dir"

for agent in claude codex; do
  target="$bin_dir/sbx-$agent"
  cat > "$target" <<EOF
#!/usr/bin/env bash
set -euo pipefail

# Generated by $sbx_dir/install.sh — re-run it if this file moves.
doppler_project=""
doppler_config=""

while [[ \$# -gt 0 ]]; do
  case "\$1" in
    --doppler-project) doppler_project="\$2"; shift 2 ;;
    --doppler-config) doppler_config="\$2"; shift 2 ;;
    *) break ;;
  esac
done

if [[ -z "\$doppler_project" || -z "\$doppler_config" ]]; then
  echo "Usage: \$(basename "\$0") --doppler-project <project> --doppler-config <config> [sbx env run args...]" >&2
  exit 1
fi

exec sbx env run "$sbx_dir/sbxenv.yaml" "$sbx_dir/sbxenv.$agent.yaml" \\
  --env-arg workspace="\$PWD" \\
  --env-arg doppler_project="\$doppler_project" \\
  --env-arg doppler_config="\$doppler_config" \\
  "\$@"
EOF
  chmod +x "$target"
  echo "installed $target -> $sbx_dir/sbxenv.$agent.yaml"
done
