#!/usr/bin/env bash
set -euo pipefail

sbx_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
bin_dir="$HOME/.local/bin"
mkdir -p "$bin_dir"

target="$bin_dir/aibox"
cat > "$target" <<EOF
#!/usr/bin/env bash
set -euo pipefail

# Generated by $sbx_dir/install.sh — re-run it if this file moves.
sbx_dir="$sbx_dir"

usage() {
  echo "Usage: \$(basename "\$0") <agent> --doppler-project <project> --doppler-config <config> [sbx env run args...]" >&2
  available="\$(cd "\$sbx_dir" && ls sbxenv.*.yaml 2>/dev/null | grep -v '^sbxenv\.yaml\$' | sed -E 's/^sbxenv\.(.*)\.yaml\$/\1/' | tr '\n' ' ')"
  echo "Available agents: \${available:-none found}" >&2
}

agent="\${1:-}"
if [[ -z "\$agent" ]]; then
  usage
  exit 1
fi
shift

agent_file="\$sbx_dir/sbxenv.\$agent.yaml"
if [[ ! -f "\$agent_file" ]]; then
  echo "Error: no \$agent_file" >&2
  usage
  exit 1
fi

doppler_project=""
doppler_config=""

while [[ \$# -gt 0 ]]; do
  case "\$1" in
    --doppler-project) doppler_project="\$2"; shift 2 ;;
    --doppler-config) doppler_config="\$2"; shift 2 ;;
    *) break ;;
  esac
done

if [[ -z "\$doppler_project" || -z "\$doppler_config" ]]; then
  usage
  exit 1
fi

exec sbx env run "\$sbx_dir/sbxenv.yaml" "\$agent_file" \\
  --env-arg workspace="\$PWD" \\
  --env-arg doppler_project="\$doppler_project" \\
  --env-arg doppler_config="\$doppler_config" \\
  "\$@"
EOF
chmod +x "$target"
echo "installed $target -> $sbx_dir (agent selected by first argument, e.g. 'aibox claude')"
