#!/usr/bin/env bash
set -euo pipefail

sbx_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
envs_dir="${1:-$sbx_dir/envs}"

if [[ ! -d "$envs_dir" ]]; then
  echo "Error: no such directory: $envs_dir" >&2
  exit 1
fi
envs_dir="$(cd "$envs_dir" && pwd)"

if [[ ! -f "$envs_dir/sbxenv.yaml" ]]; then
  echo "Error: $envs_dir/sbxenv.yaml not found" >&2
  exit 1
fi

bin_dir="$HOME/.local/bin"
mkdir -p "$bin_dir"

target="$bin_dir/aibox"
cat > "$target" <<EOF
#!/usr/bin/env bash
set -euo pipefail

# Generated by $sbx_dir/install.sh — re-run it (optionally with a new envs
# directory path as its argument) if this file moves.
envs_dir="$envs_dir"
config_file="\${XDG_CONFIG_HOME:-\$HOME/.config}/aibox/config.yaml"

usage() {
  echo "Usage: \$(basename "\$0") <agent> [--doppler-project <project>] [--doppler-config <config>] [sbx env run args...]" >&2
  echo "Falls back to \$config_file for doppler_project/doppler_config when not passed as flags." >&2
  available="\$(cd "\$envs_dir" && ls sbxenv.*.yaml 2>/dev/null | grep -v '^sbxenv\.yaml\$' | sed -E 's/^sbxenv\.(.*)\.yaml\$/\1/' | tr '\n' ' ')"
  echo "Available agents: \${available:-none found}" >&2
}

agent="\${1:-}"
if [[ -z "\$agent" ]]; then
  usage
  exit 1
fi
shift

agent_file="\$envs_dir/sbxenv.\$agent.yaml"
if [[ ! -f "\$agent_file" ]]; then
  echo "Error: no \$agent_file" >&2
  usage
  exit 1
fi

doppler_project=""
doppler_config=""

while [[ \$# -gt 0 ]]; do
  case "\$1" in
    --doppler-project) doppler_project="\$2"; shift 2 ;;
    --doppler-config) doppler_config="\$2"; shift 2 ;;
    *) break ;;
  esac
done

config_value() {
  local key="\$1"
  [[ -f "\$config_file" ]] || return 0
  awk -F': *' -v k="\$key" '\$1==k {print \$2; exit}' "\$config_file"
}

[[ -n "\$doppler_project" ]] || doppler_project="\$(config_value doppler_project)"
[[ -n "\$doppler_config" ]] || doppler_config="\$(config_value doppler_config)"

if [[ -z "\$doppler_project" || -z "\$doppler_config" ]]; then
  usage
  exit 1
fi

exec sbx env run "\$envs_dir/sbxenv.yaml" "\$agent_file" \\
  --env-arg workspace="\$PWD" \\
  --env-arg doppler_project="\$doppler_project" \\
  --env-arg doppler_config="\$doppler_config" \\
  "\$@"
EOF
chmod +x "$target"
echo "installed $target -> $envs_dir (agent selected by first argument, e.g. 'aibox claude')"
